services:
  app:
    build: .
    container_name: guincho-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: guincho
      DB_PORT: 3306
      PORT: 3000
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: guincho-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: guincho
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: